FROM python:3.6

ENV LANG=C.UTF-8

WORKDIR /usr/src/aggregation

RUN pip install --upgrade pip

# this line is still needed until hdbscan pushes to pip next
RUN pip install cython numpy

# install dependencies
COPY setup.py .
RUN pip install .[test]

# install package
COPY . .
RUN pip install -U .[test]
