FROM python:3.7

ENV LANG=C.UTF-8

WORKDIR /usr/src/aggregation

RUN apt-get update && apt-get install  --no-install-recommends -y libgeos-dev

# install dependencies
COPY setup.py .
RUN pip install --upgrade pip
RUN pip install .[test]

# install package
COPY . .
RUN pip install -U .[test]
