version: '2'
services:
  aggregation:
    build:
      context: ./
      args:
        REVISION: fake-git-sha-id
    volumes:
      - ./panoptes_aggregation:/usr/src/aggregation/panoptes_aggregation
      - ~/.aws:/root/.aws
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_SECURITY_TOKEN=${AWS_SECURITY_TOKEN}
      - LISTEN_PORT=5000
    ports:
      - "5000:5000"
