name: Python coverage

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install panoptes aggregation
      run: |
        pip install -U pip
        pip install -U .[online,test,doc]
    - name: Run tests
      env:
        TRAVIS: true  # one test is skipped on CI and looks for this env value
      run: nosetests
    - name: Coveralls
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: coveralls --service=github
