name: Deploy to Batchagg

on:
  push:
    tags:
      - batch-aggregation
  workflow_dispatch:

jobs:
  build_and_push_image:
    name: Build and Push Image
    uses: zooniverse/ci-cd/.github/workflows/build_and_push_image.yaml@main
    with:
      repo_name: aggregation-for-caesar
      commit_id: ${{ github.sha }}
      latest: false
      build_args: "REVISION=${{ github.sha }}"

  deploy_batchagg:
    name: Deploy to Batchagg
    uses: zooniverse/ci-cd/.github/workflows/deploy_app.yaml@main
    needs: build_and_push_image
    with:
      app_name: aggregation-caesar
      repo_name: aggregation-for-caesar
      commit_id: ${{ github.sha }}
      environment: batchagg
      deploy_check: false
    secrets:
      creds: ${{ secrets.AZURE_AKS }}

  slack_notification:
    name: Slack notification
    uses: zooniverse/ci-cd/.github/workflows/slack_notification.yaml@main
    needs: deploy_batchagg
    if: always()
    with:
      commit_id: ${{ github.sha }}
      job_name: Deploy to Batchagg / deploy_app
      status: ${{ needs.deploy_production.result }}
      title: "Aggregation Batchagg deploy complete"
      title_link: "https://batchagg-aggregation-caesar.zooniverse.org"
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
