name: Publish to Test PyPi

on: workflow_dispatch

jobs:
  build-and-publish:
    name: Build python package and publish to Test PyPi
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flit
    - name: Build
      run: flit build
    - name: Publish to Test PyPi
      env:
        FLIT_USERNAME: '__token__'
        FLIT_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        FLIT_INDEX_URL: 'https://test.pypi.org/legacy/'
      run: flit publish
